# Generated by Django 5.2.10 on 2026-04-29 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('total_seats', models.PositiveIntegerField()),
                ('max_cet_rank', models.PositiveIntegerField(blank=True, help_text='Maximum CET rank allowed. Leave blank for no limit.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=50)),
                ('cgpa', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('cet_rank', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.elective')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electives.student')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.elective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.student')),
            ],
            options={
                'ordering': ['student', 'rank'],
                'unique_together': {('student', 'elective'), ('student', 'rank')},
            },
        ),
    ]
